dist: trusty
language: java
jdk: oraclejdk8
notifications:
  email:
    - alvestcas@alum.us.es
    on_success: never
    on_failure: always
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
branches:
  only:
  - master
  - develop