CREATE DATABASE IF NOT EXISTS inmocasa;

ALTER DATABASE inmocasa
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON inmocasa.* TO 'inmocasa@%' IDENTIFIED BY 'inmocasa';
